<a href="https://colab.research.google.com/github/Ispan32/DZNikita/blob/main/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#A Импортировать библиотеку NumPy
import numpy as np

In [2]:
#b.Создать массив из 10 нулей
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#c.Создать массив из 10 единиц
b = np.ones(10)
print (b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#d.Создать массив из 10 пятерок
c = b*5
print (c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
#e.Создать массив из целых чисел от 10 до 50
d = np.arange(10, 51)
print (d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [10]:
#f.Создать массив из четных чисел от 10 до 50
f = np.arange(10, 51, 2)
print (f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [11]:
#g.Создать матрицу 3х3 с числами от 0 до 8
z = np.arange(9).reshape(3,3)
print (z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#h.Создать единичную матрицу 3x3
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
#i.Использовать NumPy для генерации случайного числа от 0 до 1
i = np.random.rand(1)
print (i)

[0.49967435]


In [4]:
#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
j = np.random.rand(25)
print (j)


[0.01116036 0.38226726 0.20305382 0.2669051  0.08084972 0.26640223
 0.09406196 0.11509936 0.55084319 0.57408115 0.89465576 0.32364814
 0.08829364 0.39738592 0.28184059 0.79728191 0.73824726 0.70727612
 0.26638463 0.0290153  0.23045814 0.76801413 0.67855379 0.91427374
 0.93818677]


In [5]:
#k.Создайте следующую матрицу используя функции библиотеки NumPy: 
k = np.arange(0, 1.01, 0.01)
print (k)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [6]:
# Матрица из условия задачи
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [7]:
#l Необходимо написать код который вернет следующую матрицуиз стартовой:
print('l =', mat[2:, 1:])

l = [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [8]:
#m.Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l.
ar = mat[ mat == 20]
print(ar)

[20]


In [9]:
#n.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
print('n =', mat[0:3, 1].reshape(3,1))

n = [[ 2]
 [ 7]
 [12]]


In [10]:
#o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
print('o =', mat[4:])

o = [[21 22 23 24 25]]


In [11]:
#p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
print('n =', mat[3:])

n = [[16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
#q.Получить сумму всех значений в стартовой матрице mat
print(mat.sum())

325


In [13]:
#r.Получить стандартное отклонение в стартовой матрице mat
print(mat.std())

7.211102550927978


In [14]:
#s.Получить сумму значений в колонках в стартовой матрице mat
print(mat.sum(axis=0))

[55 60 65 70 75]
